version: '3'

services:
  web:
      container_name: web
      build: .
      volumes:
        # this sync our source code to the container
        - ./var/www/html/
      links:
        - mongodb
      depends_on:
        - mongodb
      networks:
        - default
      ports:
        - "8100:80"
      stdin_open: true
      tty: true

  mongodb:
    image: mongo:latest
    container_name: mongodbs
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE = users
      - MONGODB_COLLECTION = users
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
